apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    node:
      id: envoy-1
      cluster: envoy-test
    dynamic_resources:
      lds_config:
        path_config_source:
          path: /config/lds.yaml
          watched_directory: 
            path: /config
      cds_config:
        path_config_source:
          path: /config/cds.yaml
          watched_directory: 
            path: /config
